# Generated by Django 5.2.4 on 2025-08-03 04:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesettings',
            name='check_in_end_time',
            field=models.TimeField(default=datetime.time(11, 0)),
        ),
        migrations.AddField(
            model_name='attendancesettings',
            name='check_in_grace_minutes_after',
            field=models.IntegerField(default=120),
        ),
        migrations.AddField(
            model_name='attendancesettings',
            name='check_in_grace_minutes_before',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='attendancesettings',
            name='check_in_start_time',
            field=models.TimeField(default=datetime.time(7, 0)),
        ),
        migrations.AddField(
            model_name='attendancesettings',
            name='check_out_end_time',
            field=models.TimeField(default=datetime.time(20, 0)),
        ),
        migrations.AddField(
            model_name='attendancesettings',
            name='check_out_grace_minutes_after',
            field=models.IntegerField(default=180),
        ),
        migrations.AddField(
            model_name='attendancesettings',
            name='check_out_grace_minutes_before',
            field=models.IntegerField(default=120),
        ),
        migrations.AddField(
            model_name='attendancesettings',
            name='check_out_start_time',
            field=models.TimeField(default=datetime.time(15, 0)),
        ),
    ]
